--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_dirtyread; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_dirtyread WITH SCHEMA public;


--
-- Name: EXTENSION pg_dirtyread; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pg_dirtyread IS 'Read dead but unvacuumed rows from table';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin (
    admin_id bigint NOT NULL,
    code character varying(255),
    name character varying(255),
    region character varying(255)
);


ALTER TABLE public.admin OWNER TO postgres;

--
-- Name: admin_admin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin ALTER COLUMN admin_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: device; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.device (
    release boolean NOT NULL,
    device_id bigint NOT NULL,
    device_type character varying(31) NOT NULL,
    laptop_barcode_num character varying(255),
    model_code character varying(255),
    serial_num character varying(255)
);


ALTER TABLE public.device OWNER TO postgres;

--
-- Name: device_device_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.device ALTER COLUMN device_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_device_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laptop_test_result; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laptop_test_result (
    adapter integer,
    bag integer,
    battery_report boolean,
    camera_status boolean,
    charger_status boolean,
    date date,
    keyboard_status boolean,
    laptop integer,
    mouse integer,
    mouse_pad integer,
    pic_stage integer,
    power_cable integer,
    release boolean,
    stage integer,
    usb_status boolean,
    device_device_id bigint,
    laptop_test_result_id bigint NOT NULL,
    rent_rent_id bigint,
    student_student_id bigint,
    failed_keys character varying(1000),
    battery_report_summary character varying(255),
    battery_report_url character varying(255),
    description character varying(255),
    failed_ports character varying(255),
    pdf_file_name character varying(255),
    random_key character varying(255),
    sum_of_damages integer
);


ALTER TABLE public.laptop_test_result OWNER TO postgres;

--
-- Name: laptop_test_result_laptop_test_result_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.laptop_test_result ALTER COLUMN laptop_test_result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laptop_test_result_laptop_test_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: phone_test_result; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.phone_test_result (
    device_device_id bigint,
    phone_test_result_id bigint NOT NULL
);


ALTER TABLE public.phone_test_result OWNER TO postgres;

--
-- Name: phone_test_result_phone_test_result_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.phone_test_result ALTER COLUMN phone_test_result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.phone_test_result_phone_test_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: photo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.photo (
    damage integer,
    type integer NOT NULL,
    laptop_test_result_laptop_test_result_id bigint,
    phone_test_result_phone_test_result_id bigint,
    photo_id bigint NOT NULL,
    ai_name character varying(255),
    name character varying(255)
);


ALTER TABLE public.photo OWNER TO postgres;

--
-- Name: photo_photo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.photo ALTER COLUMN photo_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.photo_photo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rent; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rent (
    release_date_time date,
    rent_date_time date,
    device_device_id bigint,
    rent_id bigint NOT NULL,
    student_student_id bigint
);


ALTER TABLE public.rent OWNER TO postgres;

--
-- Name: rent_rent_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rent ALTER COLUMN rent_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rent_rent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student (
    student_id bigint NOT NULL,
    class_num character varying(255),
    edu character varying(255),
    email character varying(255),
    name character varying(255),
    refresh_token character varying(255),
    region character varying(255),
    retire_yn character varying(255),
    ssafy_id character varying(255),
    student_num character varying(255)
);


ALTER TABLE public.student OWNER TO postgres;

--
-- Name: student_student_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student ALTER COLUMN student_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: admin; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admin (admin_id, code, name, region) FROM stdin;
1	test	test	구미
\.


--
-- Data for Name: device; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.device (release, device_id, device_type, laptop_barcode_num, model_code, serial_num) FROM stdin;
f	6	Laptop	a12345678	NT850XCJ-XB72B(10세대)	a12345678
t	7	Laptop	A10300957A	NT850XCJ-XB72B(10세대)	KUYR99YTB0008P
f	8	Laptop	😙🙃😗🥲😘😇😘😇😘😇😘😅😛😅😗😇	 NT961XGL-COM(14세대)	BUXZGFCX500145E
f	9	Laptop	A40300187A325	 NT961XGL-COM(14세대)	6UK29FCX500145E
f	10	Laptop	A10300957A	NT761XDA-X07/C(11세대)	KUYR99YwTB0008P
f	12	Laptop	A10301122A	NT761XDA-X07/C(11세대)	KRKW99YW50013F
t	11	Laptop	A10300957A	NT850XCJ-XB72B(10세대)	S/NKUYR99YTB0008P
f	13	Laptop	노을이다아아벌써저녁인가봐아	NT761XDA-X07/C(11세대)	🫠QA는 너무나 재밌어🫠
f	14	Laptop	냐냐뇨	NT761XDA-X07/C(11세대)	냐냐뇨
\.


--
-- Data for Name: laptop_test_result; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.laptop_test_result (adapter, bag, battery_report, camera_status, charger_status, date, keyboard_status, laptop, mouse, mouse_pad, pic_stage, power_cable, release, stage, usb_status, device_device_id, laptop_test_result_id, rent_rent_id, student_student_id, failed_keys, battery_report_summary, battery_report_url, description, failed_ports, pdf_file_name, random_key, sum_of_damages) FROM stdin;
1	1	t	f	t	2100-04-30	t	0	1	1	6	1	f	6	f	9	17	9	7	1	배터리 상태 요약:\n\n설계 용량: 73829 mWh\n현재 용량: 74496 mWh\n배터리 수명: 100.9%\n충전 횟수: 56\n배터리 상태: 양호\n예상 수명: 약 444회 충전 가능	battery_report_DESKTOP-QFN2D55_20250409_122940.html	김두영＼(^o^)／😅🤣로로밀	port1	17_7_rent.pdf	N2211	0
1	1	t	f	f	2025-04-09	f	1	1	1	6	1	f	6	f	10	18	11	8	',-,.,/,0,1,2,3,4,5,6,7,8,9,;,=,A,ALT,BACK,CAPS,CTRL,DEL,DOWN,E,ENTER,ESC,F,F1,F10,F11,F12,F2,F3,F4,F5,F6,F7,F8,F9,G,I,INS,J,LEFT,LSHIFT,N *,N /,NUM\n+,NUM\n-,NUM\n.,NUM\n0,NUM\n1,NUM\n2,NUM\n3,NUM\n4,NUM\n5,NUM\n6,NUM\n7,NUM\n8,NUM\n9,NUM\nENT,NUM\nLOCK,O,P,PRT,Q,R,RIGHT,RSHIFT,SPACE,T,TAB,U,UP,WIN,Y,Z,[,\\,],`,한/영,한자	배터리 상태 요약:\n\n설계 용량: 79844 mWh\n현재 용량: 68889 mWh\n배터리 수명: 86.28%\n충전 횟수: 221\n배터리 상태: 양호\n예상 수명: 약 279회 충전 가능	battery_report_DESKTOP-9GN5NQG_20250409_130637.html	ㅇㅇㅇ 아니야 여보세요. 좀 거칠게 썼음	port1	18_8_rent.pdf	J9135	9
1	1	t	t	f	2025-04-09	f	1	1	1	6	1	t	6	f	11	26	11	8	-,0,2,3,4,8,9,E	배터리 상태 요약:\n\n설계 용량: 79844 mWh\n현재 용량: 70580 mWh\n배터리 수명: 88.4%\n충전 횟수: 292\n배터리 상태: 양호\n예상 수명: 약 208회 충전 가능	battery_report_DESKTOP-4QCTMKG_20250409_132736.html	...	port2,port3	26_8_return.pdf	A5182	0
1	1	t	t	t	2025-04-09	t	1	1	1	6	1	f	6	t	12	43	12	2	\N	배터리 상태 요약:\n\n설계 용량: 79844 mWh\n현재 용량: 65114 mWh\n배터리 수명: 81.55%\n충전 횟수: 183\n배터리 상태: 양호\n예상 수명: 약 317회 충전 가능	battery_report_DESKTOP-4QCTMKG_20250409_152128.html		\N	43_2_rent.pdf	V8060	11
1	1	t	t	t	2025-04-09	t	1	1	1	6	1	f	6	t	13	44	14	2	\N	배터리 상태 요약:\n\n설계 용량: 79844 mWh\n현재 용량: 65114 mWh\n배터리 수명: 81.55%\n충전 횟수: 183\n배터리 상태: 양호\n예상 수명: 약 317회 충전 가능	battery_report_DESKTOP-4QCTMKG_20250409_154451.html	🤣🤣	\N	44_2_rent.pdf	L1521	8
1	1	t	t	t	2025-04-09	f	1	1	1	6	1	t	5	f	14	47	14	2	',,,-,.,/,0,1,3,4,5,6,7,8,9,;,=,A,ALT,B,BACK,C,CAPS,CTRL,D,DEL,DOWN,ENTER,ESC,F1,F10,F11,F12,F2,F3,F4,F5,F6,F7,F8,F9,I,INS,J,K,L,LEFT,LSHIFT,M,N,N *,N /,NUM\n+,NUM\n-,NUM\n.,NUM\n0,NUM\n1,NUM\n2,NUM\n3,NUM\n4,NUM\n5,NUM\n6,NUM\n7,NUM\n8,NUM\n9,NUM\nENT,NUM\nLOCK,O,P,PRT,Q,RIGHT,RSHIFT,SPACE,T,U,UP,V,WIN,X,Y,Z,[,\\,],`,한/영,한자	배터리 상태 요약:\n\n설계 용량: 79844 mWh\n현재 용량: 65114 mWh\n배터리 수명: 81.55%\n충전 횟수: 183\n배터리 상태: 양호\n예상 수명: 약 317회 충전 가능	battery_report_DESKTOP-4QCTMKG_20250409_161239.html	😆	port1,port3	\N	G6158	\N
\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	6	\N	f	2	\N	\N	45	\N	8	\N	\N	\N	\N	\N	\N	J6255	\N
\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	0	\N	f	1	\N	\N	25	\N	7	\N	\N	\N	\N	\N	\N	\N	\N
\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	0	\N	f	1	\N	\N	27	\N	3	\N	\N	\N	\N	\N	\N	\N	\N
1	1	t	t	t	2025-04-09	t	1	1	1	6	1	f	4	f	7	30	13	4	\N	배터리 상태 요약:\n\n설계 용량: 79844 mWh\n현재 용량: 70580 mWh\n배터리 수명: 88.4%\n충전 횟수: 293\n배터리 상태: 양호\n예상 수명: 약 207회 충전 가능	battery_report_DESKTOP-4QCTMKG_20250409_152558.html	\N	port2,port3	\N	J1987	\N
\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	0	\N	f	1	\N	\N	13	\N	1	\N	\N	\N	\N	\N	\N	\N	\N
\N	\N	\N	t	\N	\N	\N	\N	\N	\N	0	\N	f	1	\N	\N	46	\N	3	\N	\N	\N	\N	\N	\N	D8321	\N
1	1	f	f	f	1900-04-10	f	70	1	1	6	2	f	6	f	8	16	8	6		\N		김두영		16_6_rent.pdf	G8253	1
\.


--
-- Data for Name: phone_test_result; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.phone_test_result (device_device_id, phone_test_result_id) FROM stdin;
\.


--
-- Data for Name: photo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.photo (damage, type, laptop_test_result_laptop_test_result_id, phone_test_result_phone_test_result_id, photo_id, ai_name, name) FROM stdin;
0	3	30	\N	114	analyzed_30_3_compressed_1744179426927.jpg	30_3_compressed_1744179426927.jpg
0	4	30	\N	115	analyzed_30_4_compressed_1744179441182.jpg	30_4_compressed_1744179441182.jpg
1	4	47	\N	127	analyzed_47_4_compressed_1744182161208.jpg	47_4_compressed_1744182161208.jpg
0	1	16	\N	71	analyzed_16_1_compressed_1744167595219.jpg	16_1_compressed_1744167595219.jpg
1	2	16	\N	72	analyzed_16_2_compressed_1744167610419.jpg	16_2_compressed_1744167610419.jpg
0	3	16	\N	73	analyzed_16_3_compressed_1744167623731.jpg	16_3_compressed_1744167623731.jpg
0	4	16	\N	74	analyzed_16_4_compressed_1744167650698.jpg	16_4_compressed_1744167650698.jpg
0	5	16	\N	75	analyzed_16_5_compressed_1744167679254.jpg	16_5_compressed_1744167679254.jpg
0	6	16	\N	76	analyzed_16_6_compressed_1744167693089.jpg	16_6_compressed_1744167693089.jpg
0	1	17	\N	77	analyzed_17_1_compressed_1744169124715.jpg	17_1_compressed_1744169124715.jpg
0	2	17	\N	78	analyzed_17_2_compressed_1744169142033.jpg	17_2_compressed_1744169142033.jpg
0	3	17	\N	79	analyzed_17_3_compressed_1744169161444.jpg	17_3_compressed_1744169161444.jpg
0	4	17	\N	80	analyzed_17_4_compressed_1744169169059.jpg	17_4_compressed_1744169169059.jpg
0	5	17	\N	81	analyzed_17_5_compressed_1744169176412.jpg	17_5_compressed_1744169176412.jpg
0	6	17	\N	82	analyzed_17_6_compressed_1744169182487.jpg	17_6_compressed_1744169182487.jpg
0	6	30	\N	117	analyzed_30_6_compressed_1744179468473.jpg	30_6_compressed_1744179468473.jpg
1	6	44	\N	124	analyzed_44_6_compressed_1744180648827.jpg	44_6_compressed_1744180648827.jpg
0	1	18	\N	88	analyzed_18_1_compressed_1744171460884.jpg	18_1_compressed_1744171460884.jpg
0	2	18	\N	89	analyzed_18_2_compressed_1744171469566.jpg	18_2_compressed_1744171469566.jpg
0	3	18	\N	90	analyzed_18_3_compressed_1744171476722.jpg	18_3_compressed_1744171476722.jpg
0	4	18	\N	91	analyzed_18_4_compressed_1744171484298.jpg	18_4_compressed_1744171484298.jpg
0	5	18	\N	92	analyzed_18_5_compressed_1744171491436.jpg	18_5_compressed_1744171491436.jpg
9	6	18	\N	93	analyzed_18_6_compressed_1744171695007.jpg	18_6_compressed_1744171695007.jpg
0	1	26	\N	94	analyzed_26_1_compressed_1744174449750.jpg	26_1_compressed_1744174449750.jpg
0	5	26	\N	98	analyzed_26_5_compressed_1744175383284.jpg	26_5_compressed_1744175383284.jpg
0	3	26	\N	96	analyzed_26_3_compressed_1744172274168.jpg	26_3_compressed_1744172274168.jpg
0	4	26	\N	97	analyzed_26_4_compressed_1744172280260.jpg	26_4_compressed_1744172280260.jpg
0	6	26	\N	99	analyzed_26_6_compressed_1744172760004.jpg	26_6_compressed_1744172760004.jpg
1	5	47	\N	128	analyzed_47_5_compressed_1744182165839.jpg	47_5_compressed_1744182165839.jpg
0	2	26	\N	95	analyzed_26_2_compressed_1744175249182.jpg	26_2_compressed_1744175249182.jpg
1	5	43	\N	110	analyzed_43_5_compressed_1744179893954.jpg	43_5_compressed_1744179893954.jpg
0	1	43	\N	106	analyzed_43_1_compressed_1744178824748.jpg	43_1_compressed_1744178824748.jpg
1	2	43	\N	107	analyzed_43_2_compressed_1744178849546.jpg	43_2_compressed_1744178849546.jpg
8	3	43	\N	108	analyzed_43_3_compressed_1744178879180.jpg	43_3_compressed_1744178879180.jpg
0	4	43	\N	109	analyzed_43_4_compressed_1744178920978.jpg	43_4_compressed_1744178920978.jpg
1	6	43	\N	111	analyzed_43_6_compressed_1744179153257.jpg	43_6_compressed_1744179153257.jpg
0	1	30	\N	112	analyzed_30_1_compressed_1744179388213.jpg	30_1_compressed_1744179388213.jpg
0	1	44	\N	118	analyzed_44_1_compressed_1744180300147.jpg	44_1_compressed_1744180300147.jpg
1	2	44	\N	119	analyzed_44_2_compressed_1744181578544.jpg	44_2_compressed_1744181578544.jpg
0	5	45	\N	120	analyzed_45_5_compressed_1744180461751.jpg	45_5_compressed_1744180461751.jpg
5	3	44	\N	121	analyzed_44_3_compressed_1744180572075.jpg	44_3_compressed_1744180572075.jpg
0	4	44	\N	122	analyzed_44_4_compressed_1744180582381.jpg	44_4_compressed_1744180582381.jpg
1	5	44	\N	123	analyzed_44_5_compressed_1744180628191.jpg	44_5_compressed_1744180628191.jpg
0	5	30	\N	116	analyzed_30_5_compressed_1744181197916.jpg	30_5_compressed_1744181197916.jpg
1	2	30	\N	113	analyzed_30_2_compressed_1744181282605.jpg	30_2_compressed_1744181282605.jpg
0	1	47	\N	125	analyzed_47_1_compressed_1744182145724.jpg	47_1_compressed_1744182145724.jpg
1	6	47	\N	129	analyzed_47_6_compressed_1744182171749.jpg	47_6_compressed_1744182171749.jpg
0	6	45	\N	130	analyzed_45_6_compressed_1744183055082.jpg	45_6_compressed_1744183055082.jpg
1	2	47	\N	126	analyzed_47_2_compressed_1744182152330.jpg	47_2_compressed_1744182152330.jpg
\.


--
-- Data for Name: rent; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rent (release_date_time, rent_date_time, device_device_id, rent_id, student_student_id) FROM stdin;
\N	1900-04-10	8	8	6
\N	2100-04-30	9	9	7
2025-04-09	2025-04-09	10	11	8
\N	2025-04-09	12	12	2
\N	2025-04-09	7	13	4
2025-04-09	2025-04-09	13	14	2
\.


--
-- Data for Name: student; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.student (student_id, class_num, edu, email, name, refresh_token, region, retire_yn, ssafy_id, student_num) FROM stdin;
8	구미6반	12기	lynatic13@naver.com	정유진	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4IiwiZXhwIjoxNzQ0Nzg1NTY3fQ.74oS21feDA-EhPF4oHgr4oz2UUgwNqHt03yVf5vv7Hw	구미	N	8a819485907cfcd301909600c0da09de	\N
3	구미1반	12기	dororo737@gmail.com	도승국	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiZXhwIjoxNzQ0Nzg1ODgzfQ.Rpuhc3_opzmGjPUY3T2ADYe6UyphNj2pusw5CrA1agU	구미	N	8a819485907cfcd30190960024a707b9	\N
5	구미5반	12기	sskim629@gmail.com	김성수	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1IiwiZXhwIjoxNzQ0Nzg2OTYzfQ.mjF3jh4-ETuUOCKtX6sW7ebwqVtMHgbfOF79uyESC8I	구미	N	8a819485907cfcd301909600bf6e09d9	\N
2	구미5반	12기	unionion1388@naver.com	김정언	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiZXhwIjoxNzQ0Nzg3ODA0fQ._0uqu6Usl7hT0f_fd0imn0RCQefIYQ8GI3D8cKe6B-o	구미	N	8a819485907cfcd3019096003b1f0809	\N
1	구미3반	12기	thdgml1103@gmail.com	이송희	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzQ0NzY1Nzg3fQ.XhA1JrrfofjPfD-I1FBudY4OhZhobGtR78u6Vj_vk7w	구미	N	8a819485907cfcd301909600253907bb	\N
7	구미5반	12기	dubblx05@naver.com	김두영	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3IiwiZXhwIjoxNzQ0Nzc5OTEwfQ.HDbjxLbUNQV3Tbz31YMMNWtKCB0qjwKOMXEVWoqsYxg	구미	N	8a819485907cfcd30190960014db0782	\N
6	구미5반	12기	charlie7276@naver.com	김동현	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2IiwiZXhwIjoxNzQ0NzczNTgyfQ.YNLqDYmrQyIUU0zRwgU7mG8d2HsywuaP2AngJV1NoxQ	구미	N	8a819485907cfcd3019096002c5507d4	\N
4	구미6반	12기	leedltkdgur@naver.com	이상혁	eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0IiwiZXhwIjoxNzQ0NzgxNDE2fQ.KXBqFqOUpUE3qYG-eHpF9z513aI8DsO72lWMsEleeMc	구미	N	8a819485907cfcd301909600329607eb	\N
\.


--
-- Name: admin_admin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admin_admin_id_seq', 1, false);


--
-- Name: device_device_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.device_device_id_seq', 14, true);


--
-- Name: laptop_test_result_laptop_test_result_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.laptop_test_result_laptop_test_result_id_seq', 47, true);


--
-- Name: phone_test_result_phone_test_result_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.phone_test_result_phone_test_result_id_seq', 1, false);


--
-- Name: photo_photo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.photo_photo_id_seq', 130, true);


--
-- Name: rent_rent_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rent_rent_id_seq', 14, true);


--
-- Name: student_student_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.student_student_id_seq', 8, true);


--
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (admin_id);


--
-- Name: device device_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT device_pkey PRIMARY KEY (device_id);


--
-- Name: laptop_test_result laptop_test_result_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laptop_test_result
    ADD CONSTRAINT laptop_test_result_pkey PRIMARY KEY (laptop_test_result_id);


--
-- Name: phone_test_result phone_test_result_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phone_test_result
    ADD CONSTRAINT phone_test_result_pkey PRIMARY KEY (phone_test_result_id);


--
-- Name: photo photo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photo
    ADD CONSTRAINT photo_pkey PRIMARY KEY (photo_id);


--
-- Name: rent rent_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rent
    ADD CONSTRAINT rent_pkey PRIMARY KEY (rent_id);


--
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (student_id);


--
-- Name: rent fk2nebroc7ckoxh6e2k2axm57uv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rent
    ADD CONSTRAINT fk2nebroc7ckoxh6e2k2axm57uv FOREIGN KEY (device_device_id) REFERENCES public.device(device_id);


--
-- Name: laptop_test_result fk922chmknalelgrwwlm9yjqkfv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laptop_test_result
    ADD CONSTRAINT fk922chmknalelgrwwlm9yjqkfv FOREIGN KEY (student_student_id) REFERENCES public.student(student_id);


--
-- Name: photo fkfym3v6a85byu5ctxwxux7v9cc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photo
    ADD CONSTRAINT fkfym3v6a85byu5ctxwxux7v9cc FOREIGN KEY (phone_test_result_phone_test_result_id) REFERENCES public.phone_test_result(phone_test_result_id);


--
-- Name: photo fkj4ydoj2f3dj19i03oqrobfr2l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photo
    ADD CONSTRAINT fkj4ydoj2f3dj19i03oqrobfr2l FOREIGN KEY (laptop_test_result_laptop_test_result_id) REFERENCES public.laptop_test_result(laptop_test_result_id);


--
-- Name: laptop_test_result fkkxbx8it8egwgr2riyji45iwbg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laptop_test_result
    ADD CONSTRAINT fkkxbx8it8egwgr2riyji45iwbg FOREIGN KEY (rent_rent_id) REFERENCES public.rent(rent_id);


--
-- Name: phone_test_result fklcvb2g1cbhjxdsehiu3d1kpm7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phone_test_result
    ADD CONSTRAINT fklcvb2g1cbhjxdsehiu3d1kpm7 FOREIGN KEY (device_device_id) REFERENCES public.device(device_id);


--
-- Name: laptop_test_result fklfay017ot1kjx80wfomkinqlh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laptop_test_result
    ADD CONSTRAINT fklfay017ot1kjx80wfomkinqlh FOREIGN KEY (device_device_id) REFERENCES public.device(device_id);


--
-- Name: rent fkpc352hapbajsp6eeuepimw62k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rent
    ADD CONSTRAINT fkpc352hapbajsp6eeuepimw62k FOREIGN KEY (student_student_id) REFERENCES public.student(student_id);


--
-- PostgreSQL database dump complete
--

