--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-03-14 10:15:02

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4976 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16711)
-- Name: admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin (
    admin_id bigint NOT NULL,
    code character varying(255),
    name character varying(255),
    region character varying(255)
);


ALTER TABLE public.admin OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16710)
-- Name: admin_admin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin ALTER COLUMN admin_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16719)
-- Name: device; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.device (
    release boolean NOT NULL,
    device_id bigint NOT NULL,
    device_type character varying(31) NOT NULL
);


ALTER TABLE public.device OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16718)
-- Name: device_device_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.device ALTER COLUMN device_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_device_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16724)
-- Name: laptop; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laptop (
    device_id bigint NOT NULL,
    barcode_num character varying(255),
    model_code character varying(255),
    serial_num character varying(255)
);


ALTER TABLE public.laptop OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16732)
-- Name: laptop_test_result; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.laptop_test_result (
    battery_report boolean NOT NULL,
    camera_status boolean NOT NULL,
    charger_status boolean NOT NULL,
    date date,
    keyboard_status boolean NOT NULL,
    release boolean NOT NULL,
    step integer NOT NULL,
    usb_status boolean NOT NULL,
    device_device_id bigint,
    laptop_test_result_id bigint NOT NULL,
    battery_report_url character varying(255),
    failed_keys character varying(255),
    failed_ports character varying(255),
    pdf_url character varying(255)
);


ALTER TABLE public.laptop_test_result OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16731)
-- Name: laptop_test_result_laptop_test_result_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.laptop_test_result ALTER COLUMN laptop_test_result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laptop_test_result_laptop_test_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16739)
-- Name: phone; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.phone (
    device_id bigint NOT NULL,
    model_code character varying(255)
);


ALTER TABLE public.phone OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16745)
-- Name: phone_test_result; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.phone_test_result (
    device_device_id bigint,
    phone_test_result_id bigint NOT NULL
);


ALTER TABLE public.phone_test_result OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16744)
-- Name: phone_test_result_phone_test_result_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.phone_test_result ALTER COLUMN phone_test_result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.phone_test_result_phone_test_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16751)
-- Name: photo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.photo (
    laptop_test_result_laptop_test_result_id bigint,
    phone_test_result_phone_test_result_id bigint,
    photo_id bigint NOT NULL,
    name character varying(255),
    type character varying(255),
    url character varying(255),
    CONSTRAINT photo_type_check CHECK (((type)::text = ANY ((ARRAY['Front'::character varying, 'FrontRightEdge'::character varying, 'FrontLeftEdge'::character varying, 'Rear'::character varying, 'RearRightEdge'::character varying, 'RearLeftEdge'::character varying, 'Bottom'::character varying, 'BottomRightEdge'::character varying, 'BottomLeftEdge'::character varying, 'Display'::character varying, 'Keyboard'::character varying, 'Else'::character varying])::text[])))
);


ALTER TABLE public.photo OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16750)
-- Name: photo_photo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.photo ALTER COLUMN photo_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.photo_photo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16760)
-- Name: rent; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rent (
    release boolean NOT NULL,
    rent_id bigint NOT NULL,
    device_device_id bigint,
    student_student_id bigint
);


ALTER TABLE public.rent OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16759)
-- Name: rent_rent_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rent ALTER COLUMN rent_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rent_rent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16766)
-- Name: student; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student (
    class_num integer NOT NULL,
    student_num integer NOT NULL,
    rent_id bigint,
    student_id bigint NOT NULL,
    name character varying(255),
    region character varying(255)
);


ALTER TABLE public.student OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16765)
-- Name: student_student_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student ALTER COLUMN student_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4956 (class 0 OID 16711)
-- Dependencies: 218
-- Data for Name: admin; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.admin VALUES (1, 'test', '김성수', '구미');


--
-- TOC entry 4958 (class 0 OID 16719)
-- Dependencies: 220
-- Data for Name: device; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.device VALUES (false, 1, 'Laptop');
INSERT INTO public.device VALUES (false, 2, 'Laptop');


--
-- TOC entry 4959 (class 0 OID 16724)
-- Dependencies: 221
-- Data for Name: laptop; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.laptop VALUES (1, '1234', '14', 'a2sd123');
INSERT INTO public.laptop VALUES (2, '4321', '11', 'asd45');


--
-- TOC entry 4961 (class 0 OID 16732)
-- Dependencies: 223
-- Data for Name: laptop_test_result; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.laptop_test_result VALUES (true, true, true, '2025-03-13', true, false, 4, true, 1, 1, 'pdf-page', 'a,b', '1,2', 'pdf-page');
INSERT INTO public.laptop_test_result VALUES (true, true, true, '2025-03-11', true, false, 4, true, 2, 2, 'pdf-page', 'a,b', '1,2', 'pdf-page');


--
-- TOC entry 4962 (class 0 OID 16739)
-- Dependencies: 224
-- Data for Name: phone; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4964 (class 0 OID 16745)
-- Dependencies: 226
-- Data for Name: phone_test_result; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4966 (class 0 OID 16751)
-- Dependencies: 228
-- Data for Name: photo; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4968 (class 0 OID 16760)
-- Dependencies: 230
-- Data for Name: rent; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.rent VALUES (false, 1, 1, 3);
INSERT INTO public.rent VALUES (false, 2, 2, 4);


--
-- TOC entry 4970 (class 0 OID 16766)
-- Dependencies: 232
-- Data for Name: student; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.student VALUES (1, 1, 1, 3, '김성수', '구미');
INSERT INTO public.student VALUES (1, 3, NULL, 5, '김철수', '서울');
INSERT INTO public.student VALUES (1, 2, 2, 4, '홍길동', '대전');


--
-- TOC entry 4977 (class 0 OID 0)
-- Dependencies: 217
-- Name: admin_admin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admin_admin_id_seq', 1, true);


--
-- TOC entry 4978 (class 0 OID 0)
-- Dependencies: 219
-- Name: device_device_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.device_device_id_seq', 2, true);


--
-- TOC entry 4979 (class 0 OID 0)
-- Dependencies: 222
-- Name: laptop_test_result_laptop_test_result_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.laptop_test_result_laptop_test_result_id_seq', 2, true);


--
-- TOC entry 4980 (class 0 OID 0)
-- Dependencies: 225
-- Name: phone_test_result_phone_test_result_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.phone_test_result_phone_test_result_id_seq', 1, false);


--
-- TOC entry 4981 (class 0 OID 0)
-- Dependencies: 227
-- Name: photo_photo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.photo_photo_id_seq', 1, false);


--
-- TOC entry 4982 (class 0 OID 0)
-- Dependencies: 229
-- Name: rent_rent_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rent_rent_id_seq', 2, true);


--
-- TOC entry 4983 (class 0 OID 0)
-- Dependencies: 231
-- Name: student_student_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.student_student_id_seq', 5, true);


--
-- TOC entry 4782 (class 2606 OID 16717)
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (admin_id);


--
-- TOC entry 4784 (class 2606 OID 16723)
-- Name: device device_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT device_pkey PRIMARY KEY (device_id);


--
-- TOC entry 4786 (class 2606 OID 16730)
-- Name: laptop laptop_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laptop
    ADD CONSTRAINT laptop_pkey PRIMARY KEY (device_id);


--
-- TOC entry 4788 (class 2606 OID 16738)
-- Name: laptop_test_result laptop_test_result_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laptop_test_result
    ADD CONSTRAINT laptop_test_result_pkey PRIMARY KEY (laptop_test_result_id);


--
-- TOC entry 4790 (class 2606 OID 16743)
-- Name: phone phone_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phone
    ADD CONSTRAINT phone_pkey PRIMARY KEY (device_id);


--
-- TOC entry 4792 (class 2606 OID 16749)
-- Name: phone_test_result phone_test_result_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phone_test_result
    ADD CONSTRAINT phone_test_result_pkey PRIMARY KEY (phone_test_result_id);


--
-- TOC entry 4794 (class 2606 OID 16758)
-- Name: photo photo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photo
    ADD CONSTRAINT photo_pkey PRIMARY KEY (photo_id);


--
-- TOC entry 4796 (class 2606 OID 16764)
-- Name: rent rent_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rent
    ADD CONSTRAINT rent_pkey PRIMARY KEY (rent_id);


--
-- TOC entry 4798 (class 2606 OID 16772)
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (student_id);


--
-- TOC entry 4800 (class 2606 OID 16774)
-- Name: student student_rent_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_rent_id_key UNIQUE (rent_id);


--
-- TOC entry 4807 (class 2606 OID 16811)
-- Name: rent fk2nebroc7ckoxh6e2k2axm57uv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rent
    ADD CONSTRAINT fk2nebroc7ckoxh6e2k2axm57uv FOREIGN KEY (device_device_id) REFERENCES public.device(device_id);


--
-- TOC entry 4805 (class 2606 OID 16800)
-- Name: photo fkfym3v6a85byu5ctxwxux7v9cc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photo
    ADD CONSTRAINT fkfym3v6a85byu5ctxwxux7v9cc FOREIGN KEY (phone_test_result_phone_test_result_id) REFERENCES public.phone_test_result(phone_test_result_id);


--
-- TOC entry 4809 (class 2606 OID 16805)
-- Name: student fkj2ns1xbkooc8x9fj2yidsm7px; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT fkj2ns1xbkooc8x9fj2yidsm7px FOREIGN KEY (rent_id) REFERENCES public.rent(rent_id);


--
-- TOC entry 4806 (class 2606 OID 16795)
-- Name: photo fkj4ydoj2f3dj19i03oqrobfr2l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.photo
    ADD CONSTRAINT fkj4ydoj2f3dj19i03oqrobfr2l FOREIGN KEY (laptop_test_result_laptop_test_result_id) REFERENCES public.laptop_test_result(laptop_test_result_id);


--
-- TOC entry 4804 (class 2606 OID 16790)
-- Name: phone_test_result fklcvb2g1cbhjxdsehiu3d1kpm7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phone_test_result
    ADD CONSTRAINT fklcvb2g1cbhjxdsehiu3d1kpm7 FOREIGN KEY (device_device_id) REFERENCES public.device(device_id);


--
-- TOC entry 4802 (class 2606 OID 16780)
-- Name: laptop_test_result fklfay017ot1kjx80wfomkinqlh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laptop_test_result
    ADD CONSTRAINT fklfay017ot1kjx80wfomkinqlh FOREIGN KEY (device_device_id) REFERENCES public.device(device_id);


--
-- TOC entry 4808 (class 2606 OID 16816)
-- Name: rent fkpc352hapbajsp6eeuepimw62k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rent
    ADD CONSTRAINT fkpc352hapbajsp6eeuepimw62k FOREIGN KEY (student_student_id) REFERENCES public.student(student_id);


--
-- TOC entry 4801 (class 2606 OID 16775)
-- Name: laptop fkpne18ofdl4c406d3vcp4afaii; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.laptop
    ADD CONSTRAINT fkpne18ofdl4c406d3vcp4afaii FOREIGN KEY (device_id) REFERENCES public.device(device_id);


--
-- TOC entry 4803 (class 2606 OID 16785)
-- Name: phone fktl1jr8uoa81v7i2c3jpywk5p9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.phone
    ADD CONSTRAINT fktl1jr8uoa81v7i2c3jpywk5p9 FOREIGN KEY (device_id) REFERENCES public.device(device_id);


-- Completed on 2025-03-14 10:15:02

--
-- PostgreSQL database dump complete
--

