# python 이미지 사용
FROM python:3.11-slim

# 경로 설정
WORKDIR /app

# requirements 파일을 /app 디렉토리로 복사
COPY requirements.txt /app/requirements.txt

# 설치
RUN pip install --upgrade pip && pip install -r requirements.txt

# 코드를 컨테이너로 복사
COPY ./ /app

# 여는 포트
EXPOSE 5000

# 환경변수 정의
ENV FLASK_APP=app.py
ENV FLASK_ENV=production

# gunicorn으로 실행
CMD ["gunicorn", "--workers", "4", "--bind", "0.0.0.0:5000", "app:app"]
